services:
  postgres:
    image: postgres:13
    volumes:
      - ./docker/bootstrap/postgres:/docker-entrypoint-initdb.d
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5442:5432"